-- WARNING: This file is generated by tasty-integrate
-- Changes made will (probably) not be saved, see documentation.
{-# OPTIONS_GHC -fno-warn-missing-signatures #-}
module Main where
import qualified Data.QcIntegrated
       (prop_toPartition, prop_fromPartition,
        prop_fromTestpath_isomorphism)
import qualified Data.QcSuite (prop_buf_isomorphism)
import Test.Tasty
import Test.Tasty.QuickCheck
 
main :: IO ()
main
  = defaultMain
      (testGroup "modules"
         [testGroup "tests/Data/QcIntegrated.hs"
            [testProperty "42: prop_toPartition"
               Data.QcIntegrated.prop_toPartition,
             testProperty "186: prop_fromPartition"
               Data.QcIntegrated.prop_fromPartition,
             testProperty "429: prop_fromTestpath_isomorphism"
               Data.QcIntegrated.prop_fromTestpath_isomorphism],
          testGroup "tests/Data/QcSuite.hs"
            [testProperty "20: prop_buf_isomorphism"
               Data.QcSuite.prop_buf_isomorphism]])